repos:
-   repo: https://github.com/psf/black
    rev: 23.12.1  # Use the latest version
    hooks:
    -   id: black
        language_version: python3
        stages: [pre-commit]
        args: [--line-length=100]
        pass_filenames: true

-   repo: local
    hooks:
    -   id: git-add-after-black
        name: Stage Black reforms
        entry: git add -u
        language: system
        pass_filenames: false
        stages: [pre-commit]
        always_run: true

    -   id: python-tests
        name: Python Tests
        entry: powershell.exe -Command "cd fastapi-backend; .\venv\Scripts\activate; python -m pytest tests/"
        language: system
        pass_filenames: false
        always_run: false
        types: [python]
        stages: [pre-commit]

    -   id: python-lint
        name: Python Lint
        entry: powershell.exe -Command "cd fastapi-backend; .\venv\Scripts\activate; cd ..; python -m flake8 fastapi-backend/"
        language: system
        pass_filenames: true
        always_run: false
        types: [python]
        stages: [pre-commit]

    -   id: frontend-lint
        name: Frontend Lint
        entry: powershell.exe -Command "cd client; npm run lint"
        language: system
        pass_filenames: false
        always_run: false
        types: [file]
        stages: [pre-commit]
